export const ERR_DOC_NOT_FOUND = "ERR_DOC_NOT_FOUND";
export const ERR_DOC_NOT_PUBLISHED = "ERR_DOC_NOT_PUBLISHED";
export const ERR_SYNC_NO_CHANGES = "ERR_SYNC_NO_CHANGES";
export const ERR_SYNC_SUCCESS = "ERR_SYNC_SUCCESS";
export const ERR_SYNC_STARTED = "ERR_SYNC_STARTED";
export const ERR_API_FAILED = "ERR_API_FAILED";
export const ERR_UPLOAD_MEDIA = "ERR_UPLOAD_MEDIA";
export const ERR_FETCH_CONTENT = "ERR_FETCH_CONTENT";
